name: Tests

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
      - name: Install Jsonnet dependencies
        run: nix develop --no-write-lock-file --command jb install
      - name: Run tests
        run: nix develop --no-write-lock-file --command python3 -m unittest discover -s tests -v
